# Generated by Django 4.2.6 on 2023-10-21 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('experience', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'adverts',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('url', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.advert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.AddField(
            model_name='advert',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.company'),
        ),
        migrations.AddField(
            model_name='advert',
            name='user',
            field=models.ManyToManyField(through='database.Application', to=settings.AUTH_USER_MODEL),
        ),
    ]
